In [ ]:
city_name = "City A"
print(f"City Name = {city_name}")

temperature = 25
print(f"Temperature In Celcius = {temperature}C")

temperatureF = (9/5)*temperature + 32
print(f"Temperature In Farenheit = {temperatureF}F")

carbon_footprint = 500.75
print(f"Carbon Footprint = {carbon_footprint} kg CO2")
is_sustainable = carbon_footprint < 400
print(f"Is the city sustainable? = {is_sustainable}")

City Name = City A
Temperature In Celcius = 25C
Temperature In Farenheit = 77.0F
Carbon Footprint = 500.75 kg CO2
Is the city sustainable? = False


In [ ]:
num = (input("Enter Number = "))
ans = num.isdigit()
print(ans)

Enter Number = 32
True


In [ ]:
a = int(input("Enter first num = "))
b = int(input("Enter second num = "))
symbol = input("Enter operator = ")

if symbol == "+":
  result = a + b
elif symbol == "-":
  result = a - b
elif symbol == "*":
  result = a * b
else:
  result = a / b
print(f"result = {result}")

Enter first num = 8
Enter second num = 7
Enter operator = -
result = 1


In [ ]:
climate_data = [
    {"city": "City A", "temperature": 25, "carbon_footprint": 500},
    {"city": "City B", "temperature": 30, "carbon_footprint": 350},
    {"city": "City C", "temperature": 22, "carbon_footprint": 600},
    {"city": "City D", "temperature": 15, "carbon_footprint": 200},
    {"city": "City E", "temperature": 28, "carbon_footprint": 450},
]

high_temp_threshold = 26
high_temp_cities = [city for city in climate_data if city["temperature"] > high_temp_threshold]

print("Cities with high temperature (> 26 C) = ")
for city in high_temp_cities:
  print(f"{city['city']} - {city['temperature']} C")

Cities with high temperature (> 26 C) = 
City B - 30 C
City E - 28 C


In [ ]:
energy_consumption = 1000
emission_factor = 0.475

carbon_factor = calculate_carbon_footprint(energy_consumption, emission_factor)
print(f"Carbon Footprint = {carbon_footprint} kg CO2")

NameError: name 'calculate_carbon_footprint' is not defined

In [ ]:
is_leap_year = lambda year: (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0)

# Test the lambda function
year = int(input("Enter a year: "))
print(f"{year} is a leap year: {is_leap_year(year)}")


In [ ]:
import pandas as pd

renewable_sources = ["Solar", "Wind", "Hydropower", "Geothermal", "Biomas"]

data = {
    "Project": ["Solar Farm A", "Wind Turbine X", "Hydropower Y", "Solar Roof Z", "Geothermal Plant P"],
    "Technology": ["Solar", "Wind", "Hydropower", "Solar", "Geothermal"],
    "Capacity (MW)": [150, 300, 200, 50, 100],  # Megawatts
    "Cost (Million $)": [200, 400, 350, 100, 250],  # Project cost
    "Location": ["California", "Texas", "Washington", "Nevada", "Idaho"],
    "Completion Year": [2023, 2024, 2022, 2025, 2023]
}

renewable_series = pd.Series(renewable_sources)

print("Renewable Energy Sources: ")
print(renewable_series)

In [ ]:
projects_df = pd.DataFrame(data)
projects_df = pd.DataFrame(data)
projects_df.head()

In [ ]:
import pandas as pd


projects_df = pd.DataFrame(data)


selected_rows = projects_df.iloc[[1, 2]]


print(selected_rows)

In [ ]:
projects_df.info()

In [ ]:
projects_df.describe()

In [ ]:
import pandas as pd

# Create DataFrame
projects_df = pd.DataFrame(data)

# Filter projects with capacity > 100 MW
high_capacity_projects = projects_df[projects_df['Capacity (MW)'] > 100]

# Display the result
print(high_capacity_projects)


In [ ]:
import pandas as pd

# Create DataFrame
projects_df = pd.DataFrame(data)

# Add a new column for cost per megawatt
projects_df['Cost per MW ($)'] = projects_df['Cost (Million $)'] / projects_df['Capacity (MW)']

# Display the updated DataFrame
print(projects_df)

In [ ]:
import pandas as pd

# Create DataFrame
projects_df = pd.DataFrame(data)

# Group by Technology Type and calculate total capacity
capacity_by_technology = projects_df.groupby('Technology')['Capacity (MW)'].sum()

# Display the result
print(capacity_by_technology)


In [ ]:
import numpy as np

# From a list
arr1 = np.array([1, 2, 3, 4])
# From a tuple
arr2 = np.array((5, 6, 7, 8))

print(arr1)  # Output: [1 2 3 4]
print(arr2)  # Output: [5 6 7 8]


[1 2 3 4]
[5 6 7 8]


In [ ]:
arr = np.zeros((2, 3))  # 2x3 array
print(arr)
# Output:
# [[0. 0. 0.]
#  [0. 0. 0.]]


[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr = np.ones((3, 2))  # 3x2 array
print(arr)
# Output:
# [[1. 1.]
#  [1. 1.]
#  [1. 1.]]


[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
arr = np.arange(0, 10, 2)  # Start at 0, end before 10, step by 2
print(arr)  # Output: [0 2 4 6 8]


[0 2 4 6 8]


In [ ]:
arr = np.linspace(0, 1, 5)  # 5 evenly spaced numbers between 0 and 1
print(arr)  # Output: [0.   0.25 0.5  0.75 1.  ]


[0.   0.25 0.5  0.75 1.  ]


In [ ]:
arr = np.random.rand(3, 3)  # 3x3 array
print(arr)


[[0.71019455 0.68706038 0.18577469]
 [0.03574728 0.32450034 0.85606773]
 [0.97049051 0.22134033 0.36023492]]


In [ ]:
arr = np.random.randint(0, 10, (2, 2))  # Random integers between 0 and 10
print(arr)


[[7 2]
 [3 2]]


In [ ]:
arr = np.full((2, 3), 7)  # 2x3 array filled with 7
print(arr)
# Output:
# [[7 7 7]
#  [7 7 7]]


[[7 7 7]
 [7 7 7]]


In [ ]:
arr = np.eye(3)  # 3x3 identity matrix
print(arr)
# Output:
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr = np.empty((2, 3))  # 2x3 array
print(arr)
# Output: Random uninitialized values


[[3.5e-323 3.5e-323 3.5e-323]
 [3.5e-323 3.5e-323 3.5e-323]]


In [ ]:
arr = np.fromfunction(lambda i, j: i + j, (3, 3), dtype=int)
print(arr)
# Output:
# [[0 1 2]
#  [1 2 3]
#  [2 3 4]]


[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
arr = np.fromiter(range(5), dtype=int)
print(arr)  # Output: [0 1 2 3 4]


[0 1 2 3 4]


In [ ]:
arr = np.tile([1, 2], (3, 2))  # Repeat [1, 2] in a 3x2 block
print(arr)
# Output:
# [[1 2 1 2]
#  [1 2 1 2]
#  [1 2 1 2]]


[[1 2 1 2]
 [1 2 1 2]
 [1 2 1 2]]


In [ ]:
arr = np.arange(12).reshape(3, 4)  # 3x4 array from 0-11
print(arr)
# Output:
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
import numpy as np

# Example 2D matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Flatten the matrix
flattened = matrix.flatten()

print("Original Matrix:")
print(matrix)
print("\nFlattened Matrix:")
print(flattened)


Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flattened Matrix:
[1 2 3 4 5 6 7 8 9]


In [ ]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Flatten using list comprehension
flattened = [element for row in matrix for element in row]

print(flattened)


[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
def is_palindrome(string):
    # Remove spaces and convert to lowercase
    string = string.replace(" ", "").lower()
    # Check if the string is equal to its reverse
    return string == string[::-1]

# Input from the user
input_string = input("Enter a string: ")

# Check and display the result
if is_palindrome(input_string):
    print(f'"{input_string}" is a palindrome.')
else:
    print(f'"{input_string}" is not a palindrome.')


Enter a string: NITIN
"NITIN" is a palindrome.


In [ ]:
import numpy as np

# Create an array for energy consumption (in kWh)
energy_consumption = np.array([350, 420, 300, 400, 500, 450, 380])

# Calculate basic statistics
mean = np.mean(energy_consumption)  # Mean
median = np.median(energy_consumption)  # Median
std_dev = np.std(energy_consumption)  # Standard deviation
min_value = np.min(energy_consumption)  # Minimum value
max_value = np.max(energy_consumption)  # Maximum value
total = np.sum(energy_consumption)  # Total energy consumption

# Display results
print("Energy Consumption Data:", energy_consumption)
print(f"Mean: {mean} kWh")
print(f"Median: {median} kWh")
print(f"Standard Deviation: {std_dev:.2f} kWh")
print(f"Minimum: {min_value} kWh")
print(f"Maximum: {max_value} kWh")
print(f"Total Consumption: {total} kWh")


Energy Consumption Data: [350 420 300 400 500 450 380]
Mean: 400.0 kWh
Median: 400.0 kWh
Standard Deviation: 60.71 kWh
Minimum: 300 kWh
Maximum: 500 kWh
Total Consumption: 2800 kWh


In [ ]:
import numpy as np

# Energy consumption array
energy_consumption = np.array([350, 420, 300, 400, 500, 450, 380])

# Reshape the array into different shapes
# Example 1: Reshape into 2 rows and 4 columns (requires adding one more value to match 2x4)
energy_consumption = np.append(energy_consumption, [0])  # Add a dummy value to make the size divisible by 8
reshaped_2x4 = energy_consumption.reshape(2, 4)

# Example 2: Reshape into 4 rows and 2 columns (requires removing/adjusting size)
reshaped_4x2 = energy_consumption[:8].reshape(4, 2)  # Trimming excess elements

# Example 3: Reshape into a single-column vector
reshaped_column = energy_consumption.reshape(-1, 1)

# Display reshaped arrays
print("Original Array:")
print(energy_consumption)

print("\nReshaped (2x4):")
print(reshaped_2x4)

print("\nReshaped (4x2):")
print(reshaped_4x2)

print("\nReshaped to Column Vector:")
print(reshaped_column)


Original Array:
[350 420 300 400 500 450 380   0]

Reshaped (2x4):
[[350 420 300 400]
 [500 450 380   0]]

Reshaped (4x2):
[[350 420]
 [300 400]
 [500 450]
 [380   0]]

Reshaped to Column Vector:
[[350]
 [420]
 [300]
 [400]
 [500]
 [450]
 [380]
 [  0]]


In [ ]:
import pandas as pd
import numpy as np

# Create the DataFrame
data = {
    "Energy Source": ["Solar", "Wind", "Hydropower", "Geothermal", "Biomass", "Nuclear"],
    "Energy Consumption (MWh)": [1200, np.nan, 2900, np.nan, 2500, 3200],
    "Cost (Million $)": [200, 400, np.nan, 150, 250, np.nan]
}
df = pd.DataFrame(data)

# Drop rows with any missing values
df_cleaned = df.dropna()

# Display the cleaned DataFrame
print("Original DataFrame:")
print(df)

print("\nCleaned DataFrame (rows with missing values dropped):")
print(df_cleaned)


Original DataFrame:
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          Wind                       NaN             400.0
2    Hydropower                    2900.0               NaN
3    Geothermal                       NaN             150.0
4       Biomass                    2500.0             250.0
5       Nuclear                    3200.0               NaN

Cleaned DataFrame (rows with missing values dropped):
  Energy Source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
4       Biomass                    2500.0             250.0


In [ ]:
# MinMaxScaler

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Sample data (replace with your actual data)
data = {'Capacity (MW)': [150, 300, 200, 50, 100],
        'Cost (Million $)': [200, 400, 350, 100, 250]}
df = pd.DataFrame(data)

# Create a MinMaxScaler object
scaler = MinMaxScaler()

# Fit the scaler to your data and transform it
scaled_data = scaler.fit_transform(df)

# Create a new DataFrame with the scaled data
scaled_df = pd.DataFrame(scaled_data, columns=df.columns)

# Print the scaled DataFrame
scaled_df

Capacity (MW)  Cost (Million $)
0            0.4          0.333333
1            1.0          1.000000
2            0.6          0.833333
3            0.0          0.000000
4            0.2          0.500000